---
# Add new user
- name: Add shadowsocks user.
  user:
    name: "{{ new_user }}"
    shell: /bin/bash
    groups: sudo, docker
    append: yes

# set new user password, if update_user_password is true
- block:
  - name: Generate random password.
    set_fact:
      user_password: "{{ lookup('password', '/dev/null', length=32 )}}"

  - debug:
      var: user_password
      verbosity: 0

  - name: Update user password.
    user:
      name: "{{ new_user }}"
      password: "{{ user_password|password_hash('sha512') }}"
      update_password: always

  # https://stackoverflow.com/questions/37888760/
  when: "update_user_password|default(false)|bool == true"

- name: Set authorized key for user shadowsocks copying it from current user
  authorized_key:
    user: "{{ new_user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
