---
- name: Install shadowsocks
  hosts: shadowsocks-servers
  remote_user: root

  vars:
      ansible_ssh_transfer_method: scp
      playbook:
        version: 0.0.2
  tasks:
    # activate locales:
    # langs:
    #   - it_IT.UTF-8 UTF-8
    #   - en_US.UTF-8 UTF-8
    #   - es_ES.UTF-8 UTF-8
    - name: Enable locales.
      include_role:
        name: locales
    - meta: flush_handlers

    - name: Add swap to the system.
      include_role:
        name: swap

    # TODO: resize boot partition
    # TODO: move boot partition to /

    - name: Upgrade system.
      include_role:
        name: upgrade-release

    # install basic packages
    - name: Install basic packages.
      include_role:
        name: install-basics

    # install docker
    - name: Install docker user.
      include_role:
        name: ansible-docker

    # add shadowsocks user
    - name: Add shadowsocks user.
      include_role:
        name: add-user
      vars:
        new_user: "{{ shadowsocks_user }}"

    # secure SSH
    - name: Secure SSH.
      include_role:
        name: secure-ssh

    # pull shadowsocks container
    - name: Deploy docker container for shadowsocks.
      include_role:
        name: deploy-docker-shadowsocks-libev
