---
- name: Install shadowsocks
  hosts: shadowsocks-servers
  remote_user: root

  vars:
      playbook:
        version: 0.0.2

  tasks:
    # activate locales:
    # langs:
    #   - it_IT.UTF-8 UTF-8
    #   - en_US.UTF-8 UTF-8
    #   - es_ES.UTF-8 UTF-8
    - name: Enable locales.
      include_role:
        name: locales
    - meta: flush_handlers

    - name: Add swap to the system.
      include_role:
        name: swap

    - name: Upgrade system.
      include_role:
        name: upgrade-release

    # Install basic packages:
    #   - htop
    #   - tree
    #   - lynx
    #   - colordiff
    #   - tmux
    #   - zsh
    #   - git-core
    #   - molly-guard
    #   - realpath
    #   - ntp
    #   - ntp-doc
    #   - ntpdate
    #   - gpgv2
    #   - apt-transport-https
    #   - ca-certificates
    #   - software-properties-common
    - name: Install basic packages.
      include_role:
        name: install-basics

    # install docker
    - name: Install docker user.
      include_role:
        name: ansible-docker

    - name: Add shadowsocks user.
      include_role:
        name: add-user
      vars:
        new_user: "{{ shadowsocks_user }}"

    # TODO: set new user password
    # TODO: add SSH filtering by country
    - name: Secure SSH.
      include_role:
        name: secure-ssh

    # pull shadowsocks container
    - name: Deploy docker container for shadowsocks.
      include_role:
        name: deploy-docker-shadowsocks-libev

    # adjust the logging
