---
# Change configuration of SSH to key-only

# The role does the following things:
# 1. Add identity key to authorized keys on host
# 2. Disable empty password login
#      -> PermitEmptyPasswords no
# 3. Disable remote root login
#      -> PermitRootLogin no
# 4. Disable password login
#      -> PasswordAuthentication no
# 5. Enable PAM
#      -> UsePAM yes
- name: Harden SSH configuration.
  import_role:
    name: ansible-ssh-hardening

# X11Forwarding yes -> X11Forwarding no
- name: Disable X11 forwarding.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^(\# )?X11Forwarding\s+yes$'
    line: 'X11Forwarding no'
    state: present
  notify: restart sshd

# Filter ssh connections base of IP address location
- name: Filter ssh connections base of IP address location.
  import_role:
    name: ssh-filter
