---
# defaults file for install-basics
basic_packages:
  - apt-transport-https
  - ca-certificates
  - colordiff
  - git-core
  - gpgv2
  - htop
  - isag
  - lynx
  - molly-guard
  - nmon
  - python3-pip
  - software-properties-common
  - sysstat
  - systemd-timesyncd
  - tmux
  - tree
  - vnstat
  - zsh