---
## SHADOWSOCKS variables

# role: 'add-user' (root)
update_root_password: false

# role: 'locales'
langs:
  - es_ES.UTF-8 UTF-8
  - en_US.UTF-8 UTF-8
  - it_IT.UTF-8 UTF-8

# role 'set-hostname'
hostname: shadowserver

# role: 'swap'
swapfile_size: 2G

# role 'ansible-docker'
# See also:
# https://github.com/nickjj/ansible-docker/issues/18
#
## Do you want to install Community Edition ('ce') or Enterprise Edition ('ee')?
docker_edition: "ce"

## Do you want to install Docker through the "stable" or "edge" channel?
## Stable gets updated every quarter and Edge gets updated every month.
docker_channel: "stable"

## What version of Docker do you want to install?
docker_version: "18.03.0"

# role: 'add-user' (shadowsocks)
shadowsocks_user: shadowsocks
update_user_password: false

# role 'ssh-secure'
ssh_server_ports: ['29808']
ssh_client_port: '29808'

# role 'deploy-docker-shadowsocks-libev'
shadowsocks_server_port: 443
