---
# tasks file for deploy-docker-shadowsocks-libev

# Install necessary pip packages.
# See:
#   https://github.com/ansible/ansible/issues/20492#issuecomment-313325892
- name: Upgrade pip to the latest version.
  pip:
    name: pip
    state: latest

- name: Install docker-py and docker-compose pip packages.
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - docker-py
    - docker-compose

- name: Clean-up docker, docker-py, docker-compose pip packages.
  pip:
    name: "{{item}}"
    state: absent
  with_items:
    - docker
    - docker-py
    - docker-compose

- name: Install docker-py and docker-compose pip packages.
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - docker-compose

# Docker compose file with format inline v2
- name: Run with inline v2 compose
  docker_service:
    project_name: shadowsocks
    definition:
      server:
        image: shadowsocks/shadowsocks-libev
        ports:
          - "8388:{{ shadowsocks_server_port }}/tcp"
          - "8388:{{ shadowsocks_server_port }}/udp"
        environment:
          - METHOD={{ shadowsocks_server_encryption_method }}
          - PASSWORD={{ shadowsocks_server_password }}
        restart: always
  register: docker_compose_output

- name: Assert that container is running
  assert:
    that:
      - server.shadowsocks_server_1.state.running
