---

- name: Install ccshadowsocks
  hosts: ccshadowsocks-servers
  remote_user: root
  vars:
      ansible_ssh_pipelining: yes
  tasks:
    - import_tasks: ./setup/create_swap.yml
    - import_tasks: ./setup/upgrade_release.yml
    - import_tasks: ./setup/install_basics.yml
    - name: Read configuration variables
      include_vars: ../provision/shadowsocks.yml
    - name: add SHADOWSOCKS user
      user: name="{{ SHADOWSOCKS.USER }}"
