---
- name: Install ccshadowsocks
  hosts: ccshadowsocks-servers
  remote_user: root
  vars:
      ansible_ssh_pipelining: yes
  tasks:
    - import_tasks: ./setup/locales.yml
    - import_tasks: ./setup/create_swap.yml
    - import_tasks: ./setup/upgrade_release.yml
    - import_tasks: ./setup/install_basics.yml
    - name: Read configuration variables
      include_vars: ../provision/global_vars.yml
    - name: Add SHADOWSOCKS user
      user:
        name: "{{ SHADOWSOCKS.USER }}"
        shell: /bin/bash
        groups: sudo
        append: yes
    - import_tasks: ./setup/secure_ssh.yml
    # install docker
    # install shadowsocks on docker
    # adjust the logging