---
- name: update
  apt: update_cache=yes
- name: upgrade distribution
  apt: upgrade=dist
- name: restart machine
  shell: reboot
  async: 0
  poll: 0
- name: wait for server to restart
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      delay=30
- name: upgrade packages
  apt: upgrade=full

