---
# vars file for resize-boot-partition
# Minimum /boot partition should be at least 250MiB
# See:
#   https://help.ubuntu.com/community/DiskSpace
#
# boot partition minumum size is 512 MiB
boot_partition_minimum_size: 536870910
