---
- name: Install shadowsocks
  hosts: shadowsocks-servers
  remote_user: root
  vars:
      ansible_ssh_pipelining: yes
      playbook:
        version: 0.0.1
  tasks:
    # activate locales:
    # langs:
    #   - it_IT.UTF-8 UTF-8
    #   - en_US.UTF-8 UTF-8
    #   - es_ES.UTF-8 UTF-8
    - name: Enable locales.
      include_role:
        name: locales
    - meta: flush_handlers

    - name: Add swap to the system.
      include_role:
        name: swap

    - name: Upgrade system.
      include_tasks:
        name: upgrade_release.yml

    - name: Install basic packages.
      include_tasks:
        name: install_basics.yml

    - name: Add shadowsocks user.
      include_tasks:
        name: add_user.yml

    - name: Secure SSH.
      include_tasks:
        name: secure_ssh.yml

    # install docker
    # install shadowsocks on docker
    # adjust the logging
