---
- name: update packages
  apt: update_cache=yes
# Install a list of packages with Ansible
# See:
# 
# https://www.randomhacks.co.uk/how-to-install-a-list-of-packages-with-ansible/
#
- name: Install packages
  apt:
    name={{item}}
    state=present
  with_items:
    - htop
    - tree
    - lynx
    - colordiff
    - tmux
    - zsh
    - git-core
    - molly-guard
    - realpath
    - ntp
    - ntp-doc
    - ntpdate
    - gpgv2
    - apt-transport-https
    - ca-certificates
    - software-properties-common
