---
# Change configuration of SSH to key-only
# The role does the following things:
# 1. Add identity key to authorized keys on host
# 2. Disable empty password login
#      -> PermitEmptyPasswords no
# 3. Disable remote root login
#      -> PermitRootLogin no
# 4. Disable password login
#      -> PasswordAuthentication no
# 5. Enable PAM
#      -> UsePAM yes
# X11Forwarding yes -> X11Forwarding no
- debug:
    msg: "I am in role secure_ssh and ssh_user is '{{ssh_user}}'"
- import_role: 
    name: ansible-ssh-hardening
